### ISSUE TITLE
Add Vega Editor Data Viewer

### ISSUE THREAD

**Issue by jeedo** [RandomFractals/vscode-vega-viewer#134]
So that it is easier to check the output of transforms within Vega, add a Data Viewer similar to how it also appears in the online Vega Editor.

![image](https://user-images.githubusercontent.com/1866828/165729670-99860af8-067f-495c-b3ab-a75be48a28da.png)

**Comment by RandomFractals** [comment]
Vega Viewer already provides Data dropdown in the viewer top toolbar and displays much more advanced data view for the graph data sources via Data preview extension. It's not presented in the way Vega web editor does because vscode IDE has much more sophisticated UI interface for tabs and layouts. See example: https://github.com/RandomFractals/vscode-vega-viewer#example-vega-contour-plot-preview

If this request is for inline data in vega specs, I believe vscode JSON editor covers them just fine and there are other JSON view extensions you can try to view those inline data parts.
