### ISSUE TITLE
Doesn't update the view on save (Mac)

### ISSUE THREAD

**Issue by alexfrize** [RandomFractals/vscode-vega-viewer#6]
![image](https://user-images.githubusercontent.com/22485563/50856416-7fd45500-133f-11e9-9654-3e0c3b42fc54.png)

After save:
 ![image](https://user-images.githubusercontent.com/22485563/50856386-6cc18500-133f-11e9-9ba5-ec736ba52982.png)

But when I close preview and open it again, it updates:
![image](https://user-images.githubusercontent.com/22485563/50855247-2f0f2d00-133c-11e9-8f67-aa1358e18088.png)

**Comment by alexfrize** [comment]
Tried again. Works fine.

**Comment by RandomFractals** [comment]
Should have worked in the first place. Must have been some glitch in your test dry run.

Nothing has changed in that setup since the initial alpha v. release.

I do appreciate your help in taking it for a spin and prompting me to refine usage docs!

For the curious vscode ext dev minds this is handled in a very standard way via code ext workspace api in my extension.ts and should work on all platforms where code IDE prevails :)

```ts
// refresh associated preview on Vega file save
  workspace.onDidSaveTextDocument((document: TextDocument) => {
    if (isVegaFile(document)) {
      const uri: Uri = document.uri.with({scheme: 'vega'});
      const preview: VegaPreview = previewManager.find(uri);
      if (preview) {
        preview.refresh();
      }
    }
  });
```

**Comment by StephM-W** [comment]
@RandomFractals I just experienced this after using the preview straight after installing, but without restarting VSCode.

Restarting VSCode sorted it out, perhaps the save hook isn't registered until restart?

specs: Clean install of VSCode (1.32.3, stable) and vega-viewer (3.2.1, via the marketplace) on OSX Mojave (10.14.3).

[edit]: I think it might be more because I didn't initially name my files with .vl.json or .vg.json

**Comment by RandomFractals** [comment]
@Stephanemw yes, this ext. requires `.vl.json` or `.vg.json` filename extension for those vega spec previews. This is done in order to provide Preview menues in vscode only for vega specs since there are other .json config files one might have in a project.
